// Auth
export const AUTH_CLEAR_AUTH = 'AUTH_CLEAR_AUTH'
export const AUTH_SET_AUTH = 'AUTH_SET_AUTH'
export const AUTH_SET_USER = 'AUTH_SET_USER'
export const AUTH_SET_ERROR = 'AUTH_SET_ERROR'

// Board
export const SET_ACTIVE_BOARD = 'BOARD_SET_ACTIVE_BOARD'
export const SET_ACTIVE_TASK = 'BOARD_SET_ACTIVE_TASK'
