// Auth
export const AUTH_UPDATE_TOKEN = 'AUTH_UPDATE_TOKEN'
export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER'
export const AUTH_UPDATE_LOADING = 'AUTH_UPDATE_LOADING'
export const AUTH_UPDATE_ERROR = 'AUTH_UPDATE_ERROR'
